version: "3"

services:
  server_manager:
    image: cartesi/host-server-manager:0.9.0
    ports:
      - "5004:5004"
    environment:
      - RUST_LOG=warn

  advance_runner:
    environment:
      - SNAPSHOT_ENABLED=false
