name: honeypotv2-mainnet
services:
  prt-node:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - honeypotv2:mainnet
      args:
        HONEYPOT_SNAPSHOT: 0x615acc9fb8ae058d0e45c0d12fa10e1a6c9e645222c6fd94dfeda194ee427c14
        HONEYPOT_VERSION: 2.0.0
        HONEYPOT_CHAIN_NAME: mainnet
        HONEYPOT_CHECKSUM: 3ac94517756af3e57b3130ed71b2399fe5f23db4450693ae8321d32890aa95b9
    volumes:
      - state:/var/lib/cartesi-rollups-prt-node/state
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2GiB
    environment:
      WEB3_CHAIN_ID: 1
      APP_ADDRESS: 0x4c1e74ef88a75c24e49eddd9f70d82a94d19251c
      MACHINE_PATH: /var/lib/cartesi-rollups-prt-node/snapshots/0x615acc9fb8ae058d0e45c0d12fa10e1a6c9e645222c6fd94dfeda194ee427c14
      RUST_LOG: info
      STATE_DIR: /var/lib/cartesi-rollups-prt-node/state
      WEB3_PRIVATE_KEY: ${WEB3_PRIVATE_KEY}
      WEB3_RPC_URL: ${WEB3_RPC_URL}

volumes:
  state:
    driver: local
