name: honeypotv3-sepolia
services:
  prt-node:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - honeypot:v3-sepolia
      args:
        HONEYPOT_SNAPSHOT: 0xa0e299c59a356252c0723bd2cea8260547836aee5a1549dbcf2fc85b0d536845
        HONEYPOT_VERSION: 3.0.0
        HONEYPOT_CHAIN_NAME: sepolia
        HONEYPOT_CHECKSUM: 00d646bb4e9bc23e086bac283020c5d9e6f6824dbf9b1edba9c8c84a1a8d9caa
    volumes:
      - state:/var/lib/cartesi-rollups-prt-node/state
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2GiB
    environment:
      WEB3_CHAIN_ID: 11155111
      APP_ADDRESS: 0xb72d7AfbE7afd35C82D1d0B3D9C714944ff5B7d8
      MACHINE_PATH: /var/lib/cartesi-rollups-prt-node/snapshots/0xa0e299c59a356252c0723bd2cea8260547836aee5a1549dbcf2fc85b0d536845
      RUST_LOG: info
      STATE_DIR: /var/lib/cartesi-rollups-prt-node/state
      WEB3_PRIVATE_KEY: ${WEB3_PRIVATE_KEY}
      WEB3_RPC_URL: ${WEB3_RPC_URL}

volumes:
  state:
    driver: local
